<?php

return [
    //site controller
    "" => 'site/index',
    '/' => 'site/index',
    'price' => 'site/price',
    'faq' => 'site/faq',
    'about-us' => 'site/aboutus',
    'contact-us' => 'site/contact',
    'designers' => 'site/designer',
    'designers-detail/<id>/<title>' => 'site/designerDetail',
    'manufacturers' => 'site/manufacturer',
    'manufacturer-detail/<id>/<title>' => 'site/manufacturerDetail',
    'how-it-works' => 'site/howitworks',
    'search' => 'user/search',
    'search-result' => 'user/searchResult',
    'FAQ' => 'site/faq',
    'gallery' => 'site/gallery',
    //'bid-image'=>'bothDashBoard/showBidImage',
    'registration/<id>/verification' => 'site/user_acc_verification',
    //user controller
    'user/signup' => 'user/signupStep1',
    'user/signup/package' => 'user/signupStep2',
    'user/signup/payment' => 'user/signupStep3',
    'user/signup/success' => 'user/signupSuccess',
    'signup' => 'site/signup',
    'Dashboard' => 'user/bothDashboard',
    'post-project' => 'user/jobPost',
    'post-project-confirmation/<id>' => 'user/jobConfirmation',
    'bid-confirmation/<id>' => 'bothDashboard/bidConfirmation',
    'all-projects' => 'user/jobs',
    'all-purchased-designs' => 'user/purchasedDesigns',
    'design-detail/<id>' => 'manufacturerDashboard/jobDetails',
    'submitted-bids' => 'manufacturerDashboard/submittedBids',
    'upload-catalog' => 'manufacturerDashboard/uploadCatalog',
    'manufacturer-catalog' => 'manufacturerDashboard/manufacturerCatalog',
    'catalog-confirmation/<id>' => 'manufacturerDashboard/catalogConfirmation',
    'catalog-confirmation/<id>' => 'bothDashboard/catalogConfirmation',
    'project-detail/<id>' => 'bothDashboard/jobDetails',
    'submitted-design-detail/<id>' => 'bothDashboard/submittedDesignDetails',
    'bought-design-detail/<id>' => 'bothDashboard/boughtDesignDetails',
    'submit-catalog' => 'bothDashboard/catalog',
    'purchased-manufacturer-catalogs' => 'bothDashboard/purchasedMnaufacturerCatalogs',
    'purchased-catalog' => 'manufacturerDashboard/purchasedCatalog',
    'page-setting' => 'bothDashboard/pageSetting',
    'checkout' => 'transaction/checkout',
    'bid/<id>/<add>' => 'transaction/addItem',
    'pay-now' => 'transaction/payNow',
    'payment-confirm' => 'transaction/confirm',
    'ManufacturerDashboard' => 'user/manufactureDashboard',
    'manufacturer-signup' => 'site/manufactureSignup',
    'login' => 'site/login',
    'about-us' => 'site/cmsContent/slug/about_us',
    'privacy-policy' => 'site/cmsContent/slug/privacy_policy',
    'terms-and-conditions' => 'site/cmsContent/slug/tc',
    'faq' => 'site/cmsContent/slug/faq',
    //'how-it-works' => 'site/cmsContent/slug/how_it_works',
    'acceptable-use-policy' => 'site/cmsContent/slug/acceptable_use_policy',
    'user/forgotpassword' => 'user/forgotpassword',
    'user/resetpassword' => 'user/resetpassword',
    'sns-auth' => 'site/SocialSiteLogin',
    'sns-auth/<service:(google|google-oauth|facebook|linkedin|twitter)>/<type:(employee|manufacturer)>' => 'site/SocialSiteLogin',
    //'man-sns-auth' =>'site/manufactureSocialSiteLogin',
    //'man-sns-auth/<service:(google|google-oauth|facebook|linkedin|twitter)>' =>'site/manufactureSocialSiteLogin',
    //'post-project' => 'bothDashboard/jobPost'
    'chat' => 'chat/conversation',
    'chat' => 'chat/ManufacturerConversation',
    
    /** dispute controller **/
    'dispute-list'=>'dispute/disputeServices',
    'dispute-reviews/<disputeThreadId>'=>'dispute/conversations',
    /** end of dispute controller **/
];
